<a href="https://colab.research.google.com/github/samvrudhi-m-d/assesment/blob/main/meditrack_by_samvrudhi_md.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/meditrack_dataset.csv")
df.head()

,PatientID,PatientName,DOB,Phone,PrescriptionID,MedicationName,Dosage,Quantity,DoctorName,DateIssued,ExpiryDate,StockQuantity,UnitPrice,TotalAmount,PaymentStatus
0,P000001,James Clyde,1982-12-22,+1-363-131-3339,RX000001,Rivaroxaban,15ml,100,Dr. Anderson,2023-05-18,NaN,1933.0,13.53,1353.0,Overdue
1,P000002,Sean Harris,NaN,+1-278-687-3255,RX000002,Hydrocodone,250mg,90,Dr. Taylor,2024-07-24,2025-07-24,2044.0,82.02,7381.8,Partial
2,P000003,Andrew Looper,1995-08-07,NaN,RX000003,Levothyroxine,20mg,20,Dr. Thomas,2025-07-14,2026-07-14,1414.0,213.94,4278.8,Partial
3,P000004,Megan Lora,1985-09-10,+1-507-971-3580,RX000004,Atorvastatin,0.5mg,20,Dr. White,2025-11-07,2026-11-07,1836.0,199.46,3989.2,Cancelled
4,P000005,NaN,2001-09-05,+1-826-188-2077,RX000005,Naproxen,500mg,100,Dr. Moore,2025-04-18,2026-04-18,4709.0,133.80,13380.0,Pending

In [3]:
df.tail()

,PatientID,PatientName,DOB,Phone,PrescriptionID,MedicationName,Dosage,Quantity,DoctorName,DateIssued,ExpiryDate,StockQuantity,UnitPrice,TotalAmount,PaymentStatus
19995,P019996,NaN,2001-10-26,+1-803-609-3204,RX019996,Tramadol,20mg,30,Dr. Davis,2025-12-27,2026-12-27,2705.0,248.47,7454.10,Partial
19996,P019997,Eric Azar,1957-02-09,+1-613-578-4195,RX019997,Pantoprazole,50mg,20,Dr. Davis,2023-10-23,NaN,1924.0,211.71,4234.20,Partial
19997,P019998,James Sierra,2001-03-26,+1-288-566-3269,RX019998,Losartan,5mg,30,Dr. Davis,2025-11-28,2026-11-28,NaN,243.29,7298.70,Partial
19998,P019999,Roosevelt Johnson,1974-10-07,+1-961-781-1643,RX019999,Lisinopril,2mg,60,Dr. Brown,2024-07-06,2025-07-06,347.0,236.29,14177.40,Pending
19999,P020000,Kathleen Foster,1976-07-23,+1-285-620-8808,RX020000,Morphine,500mg,15,Dr. Williams,2025-10-07,2026-10-07,4745.0,22.89,343.35,Partial

In [4]:
df.shape

(20000, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       20000 non-null  object
 1   PatientName     17952 non-null  object
 2   DOB             18001 non-null  object
 3   Phone           18051 non-null  object
 4   PrescriptionID  20000 non-null  object
 5   MedicationName  20000 non-null  object
 6   Dosage          20000 non-null  object
 7   Quantity        20000 non-null  int64
 8   DoctorName      20000 non-null  object
 9   DateIssued      20000 non-null  object
 10  ExpiryDate      18010 non-null  object
 11  StockQuantity   18023 non-null  float64
 12  UnitPrice       20000 non-null  float64
 13  TotalAmount     20000 non-null  float64
 14  PaymentStatus   20000 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 2.3+ MB

In [6]:
df.columns

Index(['PatientID', 'PatientName', 'DOB', 'Phone', 'PrescriptionID',
       'MedicationName', 'Dosage', 'Quantity', 'DoctorName', 'DateIssued',
       'ExpiryDate', 'StockQuantity', 'UnitPrice', 'TotalAmount',
       'PaymentStatus'],
      dtype='object')

In [7]:
df.describe()

           Quantity  StockQuantity     UnitPrice   TotalAmount
count  20000.000000   18023.000000  20000.000000  20000.000000
mean      67.268750    2488.741830    127.540668   8552.919318
std       52.033013    1452.437948     70.591641   8912.410110
min       10.000000       0.000000      5.010000     50.600000
25%       20.000000    1222.000000     66.920000   2044.650000
50%       60.000000    2491.000000    127.125000   4978.000000
75%      100.000000    3755.000000    188.540000  12311.550000
max      180.000000    5000.000000    249.990000  44967.600000

In [8]:
df.isnull().sum()

PatientID            0
PatientName       2048
DOB               1999
Phone             1949
PrescriptionID       0
MedicationName       0
Dosage               0
Quantity             0
DoctorName           0
DateIssued           0
ExpiryDate        1990
StockQuantity     1977
UnitPrice            0
TotalAmount          0
PaymentStatus        0
dtype: int64

In [9]:
print(df.drop_duplicates())

      PatientID        PatientName         DOB            Phone  \
0       P000001        James Clyde  1982-12-22  +1-363-131-3339
1       P000002        Sean Harris         NaN  +1-278-687-3255
2       P000003      Andrew Looper  1995-08-07              NaN
3       P000004         Megan Lora  1985-09-10  +1-507-971-3580
4       P000005                NaN  2001-09-05  +1-826-188-2077
...         ...                ...         ...              ...
19995   P019996                NaN  2001-10-26  +1-803-609-3204
19996   P019997          Eric Azar  1957-02-09  +1-613-578-4195
19997   P019998       James Sierra  2001-03-26  +1-288-566-3269
19998   P019999  Roosevelt Johnson  1974-10-07  +1-961-781-1643
19999   P020000    Kathleen Foster  1976-07-23  +1-285-620-8808

      PrescriptionID MedicationName Dosage  Quantity    DoctorName  \
0           RX000001    Rivaroxaban   15ml       100  Dr. Anderson
1           RX000002    Hydrocodone  250mg        90    Dr. Taylor
2           RX000003  Levothyroxine   20mg        20    Dr. Thomas
3           RX000004   Atorvastatin  0.5mg        20     Dr. White
4           RX000005       Naproxen  500mg       100     Dr. Moore
...              ...            ...    ...       ...           ...
19995       RX019996       Tramadol   20mg        30     Dr. Davis
19996       RX019997   Pantoprazole   50mg        20     Dr. Davis
19997       RX019998       Losartan    5mg        30     Dr. Davis
19998       RX019999     Lisinopril    2mg        60     Dr. Brown
19999       RX020000       Morphine  500mg        15  Dr. Williams

       DateIssued  ExpiryDate  StockQuantity  UnitPrice  TotalAmount  \
0      2023-05-18         NaN         1933.0      13.53      1353.00
1      2024-07-24  2025-07-24         2044.0      82.02      7381.80
2      2025-07-14  2026-07-14         1414.0     213.94      4278.80
3      2025-11-07  2026-11-07         1836.0     199.46      3989.20
4      2025-04-18  2026-04-18         4709.0     133.80     13380.00
...           ...         ...            ...        ...          ...
19995  2025-12-27  2026-12-27         2705.0     248.47      7454.10
19996  2023-10-23         NaN         1924.0     211.71      4234.20
19997  2025-11-28  2026-11-28            NaN     243.29      7298.70
19998  2024-07-06  2025-07-06          347.0     236.29     14177.40
19999  2025-10-07  2026-10-07         4745.0      22.89       343.35

      PaymentStatus
0           Overdue
1           Partial
2           Partial
3         Cancelled
4           Pending
...             ...
19995       Partial
19996       Partial
19997       Partial
19998       Pending
19999       Partial

[20000 rows x 15 columns]

In [10]:
df["PatientName"] = df["PatientName"].fillna("Not Provided")

df["Phone"] = df["Phone"].fillna("Not Provided")

df["StockQuantity"] = df["StockQuantity"].fillna(df["StockQuantity"].median())

In [11]:
df.isnull().sum()

PatientID            0
PatientName          0
DOB               1999
Phone                0
PrescriptionID       0
MedicationName       0
Dosage               0
Quantity             0
DoctorName           0
DateIssued           0
ExpiryDate        1990
StockQuantity        0
UnitPrice            0
TotalAmount          0
PaymentStatus        0
dtype: int64

In [12]:
df["DOB"] = df["DOB"].fillna(df["DOB"].mode()[0])

df["ExpiryDate"] = df["ExpiryDate"].fillna(df["ExpiryDate"].mode()[0])

In [13]:
df.isnull().sum()

PatientID         0
PatientName       0
DOB               0
Phone             0
PrescriptionID    0
MedicationName    0
Dosage            0
Quantity          0
DoctorName        0
DateIssued        0
ExpiryDate        0
StockQuantity     0
UnitPrice         0
TotalAmount       0
PaymentStatus     0
dtype: int64

In [18]:
print(df["DOB"].head(10))
print(df["DateIssued"].head(10))
print(df["ExpiryDate"].head(10))

0    1982-12-22
1           NaN
2    1995-08-07
3    1985-09-10
4    2001-09-05
5    1999-09-21
6    1966-04-21
7    2005-01-03
8    1954-12-02
9    1956-06-08
Name: DOB, dtype: object
0    2023-05-18
1    2024-07-24
2    2025-07-14
3    2025-11-07
4    2025-04-18
5    2025-11-27
6    2025-10-26
7    2023-03-04
8    2023-10-22
9    2024-08-17
Name: DateIssued, dtype: object
0           NaN
1    2025-07-24
2    2026-07-14
3    2026-11-07
4    2026-04-18
5    2026-11-27
6    2026-10-26
7    2024-03-03
8    2024-10-21
9    2025-08-17
Name: ExpiryDate, dtype: object

In [21]:

date_columns = ["DOB", "DateIssued", "ExpiryDate"]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        format="%d-%m-%Y",
        errors="coerce"
    )

print(df[date_columns].dtypes)
print(df[date_columns].head(10))

DOB           datetime64[ns]
DateIssued    datetime64[ns]
ExpiryDate    datetime64[ns]
dtype: object
  DOB DateIssued ExpiryDate
0 NaT        NaT        NaT
1 NaT        NaT        NaT
2 NaT        NaT        NaT
3 NaT        NaT        NaT
4 NaT        NaT        NaT
5 NaT        NaT        NaT
6 NaT        NaT        NaT
7 NaT        NaT        NaT
8 NaT        NaT        NaT
9 NaT        NaT        NaT

In [23]:

df.to_csv("cleaned_data.csv", index=False)

from google.colab import files
files.download("cleaned_data.csv")